export const AmapErrorCode = {
  PERMISSION_INFLATION:      'PERMISSION_INFLATION',
  EXPIRY_VIOLATION:          'EXPIRY_VIOLATION',
  CONSTRAINT_RELAXATION:     'CONSTRAINT_RELAXATION',
  INVALID_SIGNATURE:         'INVALID_SIGNATURE',
  INVALID_REQUEST_SIGNATURE: 'INVALID_REQUEST_SIGNATURE',
  BROKEN_CHAIN:              'BROKEN_CHAIN',
  TOKEN_EXPIRED:             'TOKEN_EXPIRED',
  NONCE_REPLAYED:            'NONCE_REPLAYED',
  AGENT_REVOKED:             'AGENT_REVOKED',
  AGENT_UNKNOWN:             'AGENT_UNKNOWN',
  PARAMETER_LOCK_VIOLATION:  'PARAMETER_LOCK_VIOLATION',
  STALE_REQUEST:             'STALE_REQUEST',
} as const

export type AmapErrorCode = typeof AmapErrorCode[keyof typeof AmapErrorCode]
