export const AmapErrorCode = {
  // Mandate layer errors
  PERMISSION_INFLATION:       'PERMISSION_INFLATION',
  EXPIRY_VIOLATION:           'EXPIRY_VIOLATION',
  CONSTRAINT_RELAXATION:      'CONSTRAINT_RELAXATION',
  INVALID_SIGNATURE:          'INVALID_SIGNATURE',
  BROKEN_CHAIN:               'BROKEN_CHAIN',
  TOKEN_EXPIRED:              'TOKEN_EXPIRED',
  AGENT_REVOKED:              'AGENT_REVOKED',
  AGENT_UNKNOWN:              'AGENT_UNKNOWN',
  PARAMETER_LOCK_VIOLATION:   'PARAMETER_LOCK_VIOLATION',
  EXPLICIT_DENY:              'EXPLICIT_DENY',
  // Request layer errors
  NONCE_REPLAYED:             'NONCE_REPLAYED',
  STALE_REQUEST:              'STALE_REQUEST',
  INVALID_REQUEST_SIGNATURE:  'INVALID_REQUEST_SIGNATURE',
  MANDATE_HASH_MISMATCH:      'MANDATE_HASH_MISMATCH',
} as const

export type AmapErrorCode = typeof AmapErrorCode[keyof typeof AmapErrorCode]
